- name: "Git clone infra-problem"
  git:
    repo: "{{ git_repo }}"
    dest: /root/infra-problem
    accept_hostkey: yes
    key_file: /root/.ssh/id_rsa

- name: "Build static_assets image"
  docker_image:
    build:
      path: ./Dockerfile.static_assets
    name: static_assets
    tag: latest
    push: 
    source: build  

- name: "Build front-end image"
  docker_image:
    build:
      path: ./Dockerfile.front-end
    name: front-end
    tag: latest
    push:
    source: build

- name: Restart service docker 
  service:
    name: docker
    state: restarted

- name: Start static_assets
  docker_container:
    image: static_assets
    exposed_ports:  
      - 8000

- name: Start front-end
  docker_container:
    image: front-end
    exposed_ports:
      - 7878
