- name: "Add yum repository"
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL
    baseurl: https://repos.influxdata.com/rhel/7/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: Install telegraf
  yum: name=telegraf

- name: copy config
  template:
    src: telegraf.conf
    dest: "/etc/telegraf/telegraf.conf"

- name: Restart Telegraf
  service:
    name: telegraf
    state: restarted
