- name: "Git clone infra-problem"
  git:
    repo: "{{ git_repo }}"
    dest: /root/infra-problem
    accept_hostkey: yes
    key_file: /root/.ssh/id_rsa

- name: "Build newsfeed image"
  docker_image:
    build:
      path: ./Dockerfile.newsfeed
    name: newsfeed
    tag: latest
    push:
    source: build

- name: Restart service docker 
  service:
    name: docker
    state: restarted

- name: Start newsfeed
  docker_container:
    image: newsfeed
    exposed_ports:  
      - 8000
